spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.100.17.109/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 80
wechat:
  mpAppId: wxfa2442ce2335c58d
  mpAppSecret: 78c042ae71d98468441d67bde7397ec0
  token: weixinmp
  aesKey: wq5Zk1Imzo7BkGbpQLMf2zpZ4kjqB2whekt9DEJhPa4